config/routes.rb
Rails.application.routes.draw do
  resources :map, only: :index
  get 'reservations/index'
  resources :questions do 
    resources :answers 
  end 
  resources :drinks, only: [:index] 
  resources :recruits, only: [:index, :create] 
  resources :concepts, only: :index
  root "home#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :name, presence: true 
  validates :content, presence: true 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord   
  has_many :answers, dependent: :destroy 
  
  validates :name, presence: true 
  validates :title, presence: true 
  validates :content, presence: true 
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController   
  
  def create  
    @question = Question.find(params[:question_id]) 
    @answer = Answer.new  
    if @answer.update(answer_params)  
      redirect_to question_path(@question), notice: "suceess!"  
    else 
      redirect_to question_path(@question), notice: "invalid!"
  end 
end 
  def edit  
    @question = Question.find(params[:question_id]) 
    @answer = @question.answers.find(params[:id]) 
  end  

  def update  
    @question = Question.find(params[:question_id]) 
    @answer = @question.answers.find(params[:id])  
    if @answer.update(answer_params)  
      redirect_to question_path(@question), notice: "suceess!"  
    else 
      redirect_to question_path(@question), notice: "invalid!"
  end 
  end  
  def destroy  
    @question = Question.find(params[:question_id]) 
    @answer = @question.answers.find(params[:id])   
    @answer.destroy 
    redirect_to question_path(@question), notice: "delete"
  end 
  private 
  def answer_params  
    params.require(:answer).permit(:content, :name, :question_id)
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController
  def index
  end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  def index
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index 
    @questions = Question.all
  end

  def show 
    @question = Question.find(params[:id]) 
    @answer = Answer.new 
  end

  def new 
    @question = Question.new 
  end 
  def create  
    @question = Question.create(question_params) 
    if @question.save
      redirect_to questions_path, notice: "success!" 
    else 
      flash[:alert] = "save error!" 
      render :new 
    end 
  end 

  def edit 
    @question = Question.find(params[:id])
  end  
  def update  
    @question = Question.find(params[:id]) 
      if @question.update(question_params) 
        redirect_to questions_path, notice: "success!" 
      else  
        flash[:alert] = "save error!"
        render :edit 
      end 
  end   
  def destroy  
    @question = Question.find(params[:id]) 
    @question.destroy  
    redirect_to questions_path, notice: "delete!"
  end 
  private 
  def question_params 
    params.require(:question).permit(:name, :title, :content)
end 
end 

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController
  def index 

  end 
  def create 
  end 
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/recruits_helper.rb
module RecruitsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/answers/edit.html.erb
<div class="container">
<h1 class=text-center id="question.new">edit answer</h1> 
<%= form_with model: [@question, @answer], local: true do |f| %>   
<div class="form-group"> 
<label class="text-center">name</label>
<%= f.text_field :name, class: "form-control" %>  
</div> 
<div class="form-group"> 
<label class="text-center">content</label>
<%= f.text_area :content, class: "form-control" %>  
</div> 
<div class="text-center">
<%= f.submit "send", class: "btn btn-warning" %> 
</div>
<% end %> 
</div>  
<div class="text-center">
<%= link_to "HOME", root_path, class: "btn btn-warning", id: "button" %> 
</div>

app/views/concepts/index.html.erb
<%= link_to "HOME", drinks_path, class: "btn btn-warning" %>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <div class="jumbotron jumbotron-fluid" id="first-image">
  <div class="container">
    <h1 class="display-3">FREEDOM</h1>
    <p class="lead"></p>
  </div>
</div>
    </div>
    <div class="carousel-item">
      <div class="jumbotron jumbotron-fluid" id="first-image">
  <div class="container">
    <h1 class="display-3">ENTHUSIASM</h1>
    <p class="lead"></p>
  </div>
</div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div> 

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <div class="jumbotron jumbotron-fluid" id="no-image">
  <div class="container">
    <h1 class="display-3" id="concept">MILLEMIUM</h1>
  </div>
</div>
    </div>
    <div class="carousel-item">
      <div class="jumbotron jumbotron-fluid" id="no-image">
  <div class="container">
    <h1 class="display-3" id="concept">FREEDOM</h1>
    <p class="lead"></p>
  </div>
</div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div> 

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <div class="jumbotron jumbotron-fluid" id="first-image">
  <div class="container">
    <h1 class="display-3">AGAIST RACISM</h1>
    <p class="lead"></p>
  </div>
</div>
    </div>
    <div class="carousel-item">
      <div class="jumbotron jumbotron-fluid" id="first-image">
  <div class="container">
    <h1 class="display-3">HEDONISM</h1>
    <p class="lead">.</p>
  </div>
</div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div> 

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <div class="jumbotron jumbotron-fluid" id="no-image">
  <div class="container">
    <h1 class="display-3" id="concept">FREEDOM</h1>
    <p class="lead"></p>
  </div>
</div>
    </div>
    <div class="carousel-item">
      <div class="jumbotron jumbotron-fluid" id="no-image">
  <div class="container">
    <h1 class="display-3" id="concept">MILLEMIUM</h1>
    <p class="lead"></p>
  </div>
</div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div> 

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <div class="jumbotron jumbotron-fluid" id="first-image">
  <div class="container">
    <h1 class="display-3">ANTI RACISM</h1>
    <p class="lead"></p>
  </div>
</div>
    </div>
    <div class="carousel-item">
      <div class="jumbotron jumbotron-fluid" id="first-image">
  <div class="container">
    <h1 class="display-3">FREEDOM</h1>
    <p class="lead"></p>
  </div>
</div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div> 

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <div class="jumbotron jumbotron-fluid" id="no-image">
  <div class="container">
    <h1 class="display-3" id="concept">MILLEMIUM</h1>
    <p class="lead"></p>
  </div>
</div>
    </div>
    <div class="carousel-item">
      <div class="jumbotron jumbotron-fluid" id="no-image">
  <div class="container">
    <h1 class="display-3" id="concept">FREEDOM</h1>
    <p class="lead"></p>
  </div>
</div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div> 

app/views/drinks/_animation_text.html.erb
<div class="gs">
      <div class="inner"> 
          <h2 class="text">Vuenos</h2> 
          <h3 class="text">is fuckin trip</h3>
          <h3 class="text">and best chill space</h3> 
      </div>
  </div> 
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.4.1/gsap.min.js"></script> 
  <script>
          gsap.to('.text', { 
          duration:1,  
          opacity:1, 
          y:"0px", 
          yoyo:true, 
          repeat:-1,
          stagger: { 
              each:0.5, 
          }
        })   
  </script> 

app/views/drinks/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "TOP", root_path, class: "btn btn-dark", id: "top" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
      </li>
      <li class="nav-item">
        <%= link_to "HOME", drinks_path, class: "btn btn-warning" %>
      </li>
      <li class="nav-item">
        <%= link_to "CONCEPT", concepts_path, class: "btn btn-warning" %>
      </li> 


<!-- Button trigger modal -->
<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#exampleModal3" id="food">
 FOOD
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal3" tabindex="-1" role="dialog" aria-labelledby="exampleModal3Label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModal3Label">FOOD</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body"> 
      <table class="table table-hover"> 
   <thead>
    <tr>
      <th>NUMBER</th>
      <th>FOOD MENU</th>
      <th>PRICE</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>BURGER SLIDERS</td>
      <td>1280</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>CONBO SLIDERS</td>
      <td>1280</td>
    </tr> 
    <tr>
      <th scope="row">3</th>
      <td>BUFFALO CHIKEN SLIDERS</td>
      <td>1280</td>
    </tr>
    <tr>
      <th scope="row">4</th>
      <td>QUESADILLAS BUFFALO CHIKEN</td>
      <td>1280</td>
    </tr>
    <tr>
      <th scope="row">5</th>
      <td>QUESADILLAS CHEESE</td>
      <td>980</td>
    </tr>
    <tr>
      <th scope="row">6</th>
      <td>QUESADILLAS FAJITA STYLE</td>
      <td>1480</td>
    </tr>
    <tr>
      <th scope="row">7</th>
      <td>BUFFALO PLATTATER</td>
      <td>1980</td>
    </tr>
    <tr>
      <th scope="row">8</th>
      <td>LOTS.A.TOTS</td>
      <td>980</td>
    </tr>
    <tr>
      <th scope="row">9</th>
      <td>FIRE CALAMARI</td>
      <td>1000</td>
    </tr>
    <tr>
      <th scope="row">10</th>
      <td>CHEESE NACHO'S</td>
      <td>1680</td>
    </tr>
    <tr>
      <th scope="row">11</th>
      <td>CHILI NACHO'S</td>
      <td>1680</td>
    </tr>
    <tr>
      <th scope="row">12</th>
      <td>CHIKEN BREASTS STRIPS</td>
      <td>650</td>
    </tr>
    <tr>
      <th scope="row">13</th>
      <td>FRIED PICKLES</td>
      <td>700</td>
    </tr>
    <tr>
      <th scope="row">14</th>
      <td>GREEN CARRY</td>
      <td>1000</td>
    </tr>
    <tr>
      <th scope="row">15</th>
      <td>FISH &CHIPS</td>
      <td>980</td>
    </tr>
    <tr>
      <th scope="row">16</th>
      <td>BIG POTATO</td>
      <td>900</td>
    </tr>
    <tr>
      <th scope="row">17</th>
      <td>ICE</td>
      <td>300</td>
    </tr>
    <tr>
      <th scope="row">18</th>
      <td>CHEESE CAKE</td>
      <td>400</td>
    </tr>
  </tbody>
</table>
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div> 


<!-- Button trigger modal -->
<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#exampleModalScrollable" id="alchole">
  ALCHOLE
</button>

<!-- Modal -->
<div class="modal" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenteredLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
          <table class="table table-hover">
  <thead>
    <tr>
      <th>NUMBER</th>
      <th>DRINK MENU</th>
      <th>PRICE</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>BEER(GRASS)</td>
      <td>650</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>BEER</td>
      <td>800</td>
    </tr> 
    <tr>
      <th scope="row">3</th>
      <td>HEINEKEN</td>
      <td>700</td>
    </tr>
    <tr>
      <th scope="row">4</th>
      <td>HOUSE WINE</td>
      <td>600</td>
    </tr>
    <tr>
      <th scope="row">4</th>
      <td>SPAKRING WINE</td>
      <td>600</td>
    </tr>
    <tr>
      <th scope="row">5</th>
      <td>KAKU HIGHBALL</td>
      <td>700</td>
    </tr>
    <tr>
      <th scope="row">6</th>
      <td>JIM BEAM</td>
      <td>600</td>
    </tr>
    <tr>
      <th scope="row">7</th>
      <td>LEMON SOUR</td>
      <td>600</td>
    </tr>
    <tr>
      <th scope="row">8</th>
      <td>JIN TONIC</td>
      <td>700</td>
    </tr>
    <tr>
      <th scope="row">9</th>
      <td>RED EYE</td>
      <td>700</td>
    </tr>
    <tr>
      <th scope="row">10</th>
      <td>CASSIS ORANGE</td>
      <td>700</td>
    </tr>
    <tr>
      <th scope="row">11</th>
      <td>BOTTOLE WINE</td>
      <td>2480</td>
    </tr>
    <tr>
      <th scope="row">12</th>
      <td>CORA</td>
      <td>200</td>
    </tr>
    <tr>
      <th scope="row">13</th>
      <td>BREND COFFEE</td>
      <td>400</td>
    </tr>
    <tr>
      <th scope="row">14</th>
      <td>AMERICAN COFFEE</td>
      <td>400</td>
    </tr>
    <tr>
      <th scope="row">15</th>
      <td>ESPLESSO</td>
      <td>400</td>
    </tr>
    <tr>
      <th scope="row">16</th>
      <td>COCOA</td>
      <td>300</td>
    </tr>
    <tr>
      <th scope="row">17</th>
      <td>MILK</td>
      <td>200</td>
    </tr>
  </tbody>
</table>


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

      <li class="nav-item">
      <%= link_to "RECRUIT", recruits_path, class: "btn btn-warning" %>   
      </li> 
      <li class="nav-item">
      <%= link_to "QUESTIONS", questions_path, method: :get, class: "btn btn-warning" %>   
      </li> 
    </ul>  
    <li class="nav-item.1">
      <a href="https://www.facebook.com/"><i class="fa fa-facebook fa-3x" style="color: #fff;"></i></a>
      </li>  
      <li class="nav-item.1">
      <a href="https://www.twitter.com/"><i class="fa fa-twitter fa-3x" style="color: #fff;"></i></a>
      </li> 
      <li class="nav-item.1">
        <a href="https://www.instagram.com/"><i class="fa fa-instagram fa-3x" style="color: #fff;"></i></a>
      </li>  
      <li class="nav-item.1">
        <a href="https://www.youtube.com/"><i class="fa fa-youtube fa-3x" style="color: #fff;"></i></a> 
      </li> 
      <div class="title">
    Record Cafe Vuenos
    </div> 
  </div>
</nav> 

app/views/home/index.html.erb
<div class="wrap">
    <div class="inner">
        <%= link_to "Record Cafe Vuenos", drinks_path, metod: :get, id: "glitch" %> 
    </div>
</div>   
<script> 
var rand = 1000; 
function timer(){ 
  rand = Math.floor(Math.random() * (2000 - 500) + 500); 
  document.getElementById('glitch').classList.toggle('is-active'); 
  setTimeout(timer, rand); 
}  
timer(); 
</script>

app/views/questions/index.html.erb
<div class="question">
<div class="container">
<table class="table table-striped" id="question_table_striped"> 
<h1 class="text-center" id="question.table">Questions</h1>
  <thead>
    <tr>
      <th>ID</th>
      <th>NAME</th> 
      <th>TITLE</th>　
      <th>created date</th>  
      <th>updated date</th>
      <th>MENU</th>
    </tr>
  </thead>
  <tbody> 
  <% @questions.each do |question| %>
    <tr>
      <th><%= question.id %></th>
      <td><%= question.name %></td>
      <td><%= link_to question.title, question_path(question), class: "option" %></td> 
      <td><%= question.created_at.strftime("%Y年 %m月 %d日%H時%M分") %></td> 
      <td><%= question.updated_at.strftime("%Y年 %m月 %d日%H時%M分") %></td> 
      <td><%= link_to "edit", edit_question_path(question), class: "option" %> 
          <%= link_to "delete", question_path(question), 
          method: :delete, 
          data: { confirm: "Are you sure" }, class: "option" %></td>
    </tr> 
    <% end %>
  </tbody>
</table>   
<div class="text-center">
<%= link_to "new question", new_question_path, class: "btn btn-warning" %>  
</div> 
<div class="text-center">
<%= link_to "HOME", root_path, class: "btn btn-warning", id: "button"%> 
</div> 
</div> 
</div>

app/views/questions/show.html.erb
<div class="container">
<div class="card">
  <div class="card-header">
    <%= @question.title %>
  </div>
  <div class="card-body">
    <h4 class="card-title"><%= @question.content %></h4>
    <p class="card-text"><%= @question.name %></p>
  </div>
</div>   
<div class="table-main">
<h3 class="text-center" id="answers">answers</h3>
<table class="table table-striped" id="table"> 
<% if @question.answers.any? %>
  <thead>
    <tr>
      <th>name</th>
      <th>content</th>
      <th>menu</th>
    </tr>
  </thead>
  <tbody> 
  <% @question.answers.each do |answer| %>
    <tr>
      <th><%= answer.name %></th>
      <td><%= answer.content %></td>
      <td><%= link_to "edit", edit_question_answer_path(@question, answer), class: "option"%> 
          <%= link_to "delete", question_answer_path(@question, answer), 
          method: :delete, 
          data: { confirm: "Are you sure?"}, class: "option" %></td>
    </tr> 
    <% end %>  
    <% else %> 
  <h4 class="text-center">no answer yet</h4>
  <% end %>
  </tbody>  
</table> 
</div>

<div class="container">
<h1 class=text-center id="question.new">post answer</h1> 
<%= form_with model: [@question,@answer],local: true do |f| %>  
<%= f.hidden_field :question_id, { value: @question.id } %>  
<div class="form-group"> 
<label class="text-center">name</label>
<%= f.text_field :name, class: "form-control" %>  
</div> 
<div class="form-group"> 
<label class="text-center">content</label>
<%= f.text_area :content, class: "form-control" %>  
</div> 
<div class="text-center">
<%= f.submit "post", class: "btn btn-warning" %> 
</div>
<% end %> 
</div>  
</div>   
<%= link_to "home", questions_path, class: "home" %>

app/views/recruits/create.html.erb
<div class="jumbotron">
  <h2 class="display-1">THANK YOU FOR ENTRY！</h2>
  <h3 class="lead">I will contact you at later date!!</h3>
  <hr class="my-2">
  <p></p>
  <p class="lead">
    <a class="btn btn-warning btn-lg" href="/" role="button">home</a>
  </p>
</div>

app/views/recruits/index.html.erb
    <div class="text-center" id="parttime">
    <h1 class="part-title">ENTRY FORM</h1> 
    <div class="form-group">
      <label for="name">name</label>
      <input type="text" id="name" class="name" placeholder="name">
    </div> 
    <div class="form-group">
      <label for="email">email</label>
      <input type="text" id="email" class="email" placeholder="email">
    </div>  
    <div class="form-group">
      <label for="tell">phone</label>
      <input type="tell" id="tell" class="tell" placeholder="phone number">
    </div>  
    <div class="form-group">
      <label for="tell">age</label>
      <input type="age" id="age" class="age" placeholder="age">
    </div> 
    <div class="form-group">
      <label>
      <input type="radio" name="gender" value="male" checked>male 
      </label> 
      <label>
      <input type="radio" name="gender" value="male">female
      </label>
    </div>    
    <div class="form-group">
    <label for="job">current job</label>
    <select class="custom-select">
      <option selected>選択してください</option>
      <option value="1">大学生</option>
      <option value="2">専門学生</option>
      <option value="3">フリーター</option>
      <option value="1">会社員</option>
      <option value="2">アルバイト</option>
      <option value="3">自営業</option>
      <option value="3">無職</option>
      <option value="3">その他</option>
    </select>   
    </div>
    <div class="form-group" id="pr">
      <label class="pr">self PR</label>
      <textarea name="pr"></textarea>
    </div> 
    <div class="form-group">
      <label for="privacy">privacy agreement</label>
      <input type="checkbox" id="privacy" name="privacy">
    </div>   
    <div class="text-center"> 
    <%= link_to "send", recruits_path, method: :post, class: "btn btn-warning" %>
    </div>  
    </div>  
    